# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

# Workflows orchestrate a set of jobs to be run;
workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test

orbs:
  slack: circleci/slack@4.0.2

jobs:

  build-and-test:
    macos:
      xcode: 11.6.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run:
          name: Install realm/SwiftLint
          command: brew install swiftlint
      - run:
          name: Swift Linting
          command: swiftlint lint
      - run:
          name: Install nicklockwood/SwiftFormat
          command: brew install swiftformat
      - run:
          name: Swift Formating
          command: swiftformat . --lint --swiftversion 5.2
      # pre-start the simulator to prevent timeouts
      - run:
          name: Pre-start Simulator
          command: xcrun instruments -w "iPhone 8 (13.0) [" || true

      - run:
          name: Run AEPCore Tests
          command: make aep-core-unit-test

      - run:
          name: Upload Code Coverage Reports for AEPCore
          command: bash <(curl -s https://codecov.io/bash) -v -X s3 -c -D "./build/out" -J "AEPCore"

      - run:
          name: Run AEPServices Tests
          command: make aep-services-unit-test

      - run:
          name: Upload Code Coverage Reports for AEPServices
          command: bash <(curl -s https://codecov.io/bash) -v -X s3 -c -D "./build/out" -J "AEPServices"

      - run:
          name: Run AEPLifecycle Tests
          command: make aep-lifecycle-unit-test

      - run:
          name: Upload Code Coverage Reports for AEPLifecycle
          command: bash <(curl -s https://codecov.io/bash) -v -X s3 -c -D "./build/out" -J "AEPLifecycle"

      - run:
          name: Run AEPIdentity Tests
          command: make aep-identity-unit-test

      - run:
          name: Upload Code Coverage Reports for AEPIdentity
          command: bash <(curl -s https://codecov.io/bash) -v -X s3 -c -D "./build/out" -J "AEPIdentity"

      - run:
          name: Run AEPSignal Tests
          command: make aep-signal-unit-test

      - run:
          name: Upload Code Coverage Reports for AEPSignal
          command: bash <(curl -s https://codecov.io/bash) -v -X s3 -c -D "./build/out" -J "AEPSignal"

      - run:
          name: Run Integration Tests
          command: make integration-test

      # slack notification
      - slack/notify:
          channel: ${SLACK_DEFAULT_CHANNEL}
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "AEPCore [iOS] -> Build Failed :x:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project:*\n${CIRCLE_PROJECT_REPONAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\n$(date +'%m/%d/%Y %T')"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${CIRCLE_USERNAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${CIRCLE_BRANCH}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }

      - slack/notify:
          channel: ${SLACK_DEFAULT_CHANNEL}
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "AEPCore [iOS] -> Build Successful :tada:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project:*\n${CIRCLE_PROJECT_REPONAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\n$(date +'%m/%d/%Y %T')"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${CIRCLE_USERNAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${CIRCLE_BRANCH}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }
